trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo My Gradle Application!
  displayName: 'Run a one-line script'

- script: gradle build
  displayName: 'Build with gradle application'
  
- script: gradle run
  displayName: 'Running gradle application'  
